# Generated by Django 4.2.6 on 2023-11-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignment_awarded_points_assignment_total_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIUCCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='component',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Exam', 'Exam'), ('Participation', 'Participation'), ('Lab', 'Lab'), ('Project', 'Project'), ('Final Exam', 'Final Exam')], default='Assignment', max_length=200),
        ),
        migrations.AlterField(
            model_name='gradebreakdown',
            name='component',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Exam', 'Exam'), ('Participation', 'Participation'), ('Lab', 'Lab'), ('Project', 'Project'), ('Final Exam', 'Final Exam')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
