# Generated by Django 4.2.6 on 2023-11-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uiuccourse_assignment_component_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UIUCCourse',
        ),
    ]
